In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
from us import states
import gmaps

# Census & gmaps API Keys
from config import (census_key, google_key)
c = Census(census_key, year=2016)

# Configure gmaps
gmaps.configure(api_key=google_key)

In [25]:
# Run Census Search to retrieve data on all states
# Note the addition of "B23025_005E" for unemployment count
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E",
                          "B23025_005E"), {'for': 'state:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B23025_005E": "Unemployment Count",
                                      "NAME": "Name", "state": "State"})
in_census = census_pd[census_pd['Name'] == 'Indiana']
in_census

,Name,Household Income,Population,Median Age,Per Capita Income,Poverty Count,Unemployment Count,State
14,Indiana,50433.0,6589578.0,37.4,26117.0,957694.0,228929.0,18

In [29]:
# The path to our CSV file
csv_path = "2016_US_County_Level_Presidential_Results.csv"
result_df = pd.read_csv(csv_path)

#result_df.head()
in_result = result_df[result_df['state_abbr'] == 'IN']
in_clean_result = in_result.drop(['Unnamed: 0', 'diff', 'per_point_diff', 'combined_fips'], axis=1)
in_clean_result

,votes_dem,votes_gop,total_votes,per_dem,per_gop,state_abbr,county_name
795,2802.0,9642.0,13039.0,0.214894,0.739474,IN,Adams County
796,55222.0,83801.0,145787.0,0.378785,0.574818,IN,Allen County
797,9841.0,20637.0,32389.0,0.303838,0.637161,IN,Bartholomew County
798,860.0,2579.0,3654.0,0.235359,0.705802,IN,Benton County
799,1243.0,3349.0,4822.0,0.257777,0.694525,IN,Blackford County
...,...,...,...,...,...,...,...
882,2636.0,8206.0,11333.0,0.232595,0.724080,IN,Washington County
883,8322.0,16028.0,25575.0,0.325396,0.626706,IN,Wayne County
884,2585.0,9999.0,13123.0,0.196982,0.761945,IN,Wells County
885,2563.0,6813.0,9902.0,0.258837,0.688043,IN,White County
886,3379.0,11357.0,15535.0,0.217509,0.731059,IN,Whitley County

In [30]:
in_clean_result.to_csv("in_clean_result.csv", encoding="utf-8", index=False)