In [14]:
# import in and read indiana_census.csv and 2016_US_County_Level_Presidential_Results.csv files
import pandas as pd
import requests
import json
import csv

election_results_file = "in_clean_result.csv"
indiana_census_file = "indiana_census.csv"
indiana_census2_file = "indiana_census2.csv"

election_results_df = pd.read_csv(election_results_file)
indiana_census_df = pd.read_csv(indiana_census_file)
indiana_census2_df = pd.read_csv(indiana_census2_file)

In [15]:
election_results_df.head()

,votes_dem,votes_gop,total_votes,per_dem,per_gop,state_abbr,county_name
0,2802,9642,13039,0.214894,0.739474,IN,Adams County
1,55222,83801,145787,0.378785,0.574818,IN,Allen County
2,9841,20637,32389,0.303838,0.637161,IN,Bartholomew County
3,860,2579,3654,0.235359,0.705802,IN,Benton County
4,1243,3349,4822,0.257777,0.694525,IN,Blackford County

In [16]:
# Clean up county_name category. Replace 'county_name' with 'County'
election_results_df.rename(columns={"county_name":"County"}, inplace=True)
election_results_df.columns

Index(['votes_dem', 'votes_gop', 'total_votes', 'per_dem', 'per_gop',
       'state_abbr', 'County'],
      dtype='object')

In [17]:
election_results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 7 columns):
votes_dem      92 non-null int64
votes_gop      92 non-null int64
total_votes    92 non-null int64
per_dem        92 non-null float64
per_gop        92 non-null float64
state_abbr     92 non-null object
County         92 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 5.2+ KB

In [18]:
indiana_census_df.head()

,Unnamed: 0,State,County,Total Population,Population (White),Population (African-American),Population (Asian),Population (Hispanic),Median Home Value,Education (None),Education (High School),Education (GED),Education (Associates),Education (Bachelors),Education (Masters),Education (Professional),Education (Doctorate)
0,759,Indiana,Adams County,34813.0,33743.0,247.0,121.0,1533.0,114600.0,217.0,7627.0,1088.0,1594.0,2311.0,768.0,126.0,64.0
1,760,Indiana,Allen County,365565.0,290987.0,42168.0,12228.0,25810.0,116400.0,2265.0,58807.0,9682.0,23158.0,42160.0,16367.0,4152.0,1694.0
2,761,Indiana,Bartholomew County,80203.0,69108.0,1522.0,4585.0,5079.0,137500.0,527.0,15840.0,3056.0,4588.0,9685.0,5255.0,499.0,632.0
3,762,Indiana,Benton County,8709.0,8516.0,80.0,18.0,449.0,81500.0,23.0,2325.0,304.0,471.0,753.0,188.0,42.0,12.0
4,763,Indiana,Blackford County,12364.0,12036.0,75.0,38.0,176.0,67100.0,47.0,3748.0,447.0,755.0,546.0,315.0,51.0,42.0

In [19]:
indiana_census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 17 columns):
Unnamed: 0                       92 non-null int64
State                            92 non-null object
County                           92 non-null object
Total Population                 92 non-null float64
Population (White)               92 non-null float64
Population (African-American)    92 non-null float64
Population (Asian)               92 non-null float64
Population (Hispanic)            92 non-null float64
Median Home Value                92 non-null float64
Education (None)                 92 non-null float64
Education (High School)          92 non-null float64
Education (GED)                  92 non-null float64
Education (Associates)           92 non-null float64
Education (Bachelors)            92 non-null float64
Education (Masters)              92 non-null float64
Education (Professional)         92 non-null float64
Education (Doctorate)            92 non-null float64
dtypes: float64(14), int64(1), object(2)
memory usage: 12.3+ KB

In [20]:
indiana_census2_df.head()

,Unnamed: 0,County,State,Median Income,Income Per Capita,Pop in Labor Force,Pop not in Labor Force,Unemployed,Median Age,Median Age (male),Median Age (female)
0,759,Adams County,Indiana,47572.0,21173.0,15975.0,8948.0,872.0,33.7,32.0,36.0
1,760,Allen County,Indiana,49574.0,26058.0,186706.0,93216.0,13152.0,35.6,34.6,36.7
2,761,Bartholomew County,Indiana,55874.0,28631.0,41710.0,21169.0,2165.0,37.9,36.4,39.1
3,762,Benton County,Indiana,48069.0,23181.0,4368.0,2364.0,201.0,40.5,37.4,42.5
4,763,Blackford County,Indiana,38791.0,21980.0,5763.0,4263.0,480.0,43.4,42.1,45.8

In [21]:
indiana_census2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 11 columns):
Unnamed: 0                92 non-null int64
County                    92 non-null object
State                     92 non-null object
Median Income             92 non-null float64
Income Per Capita         92 non-null float64
Pop in Labor Force        92 non-null float64
Pop not in Labor Force    92 non-null float64
Unemployed                92 non-null float64
Median Age                92 non-null float64
Median Age (male)         92 non-null float64
Median Age (female)       92 non-null float64
dtypes: float64(8), int64(1), object(2)
memory usage: 8.0+ KB

In [25]:
# Merge two dataframes using an outer join
merged_file_1 = pd.merge(election_results_df, indiana_census_df, on="County", how="outer")

In [33]:
# Merge last dataframe and first merged file dataframes using an outer join
merged_file2 = pd.merge(merged_file_1, indiana_census2_df, on="County", how="outer")

In [53]:
merged_file2.head()

,votes_dem,votes_gop,total_votes,per_dem,per_gop,state_abbr,County,Unnamed: 0_x,State_x,Total Population,...,Unnamed: 0_y,State_y,Median Income,Income Per Capita,Pop in Labor Force,Pop not in Labor Force,Unemployed,Median Age,Median Age (male),Median Age (female)
0,2802,9642,13039,0.214894,0.739474,IN,Adams County,759,Indiana,34813.0,...,759,Indiana,47572.0,21173.0,15975.0,8948.0,872.0,33.7,32.0,36.0
1,55222,83801,145787,0.378785,0.574818,IN,Allen County,760,Indiana,365565.0,...,760,Indiana,49574.0,26058.0,186706.0,93216.0,13152.0,35.6,34.6,36.7
2,9841,20637,32389,0.303838,0.637161,IN,Bartholomew County,761,Indiana,80203.0,...,761,Indiana,55874.0,28631.0,41710.0,21169.0,2165.0,37.9,36.4,39.1
3,860,2579,3654,0.235359,0.705802,IN,Benton County,762,Indiana,8709.0,...,762,Indiana,48069.0,23181.0,4368.0,2364.0,201.0,40.5,37.4,42.5
4,1243,3349,4822,0.257777,0.694525,IN,Blackford County,763,Indiana,12364.0,...,763,Indiana,38791.0,21980.0,5763.0,4263.0,480.0,43.4,42.1,45.8

In [54]:
merged_file2.columns

Index(['votes_dem', 'votes_gop', 'total_votes', 'per_dem', 'per_gop',
       'state_abbr', 'County', 'Unnamed: 0_x', 'State_x', 'Total Population',
       'Population (White)', 'Population (African-American)',
       'Population (Asian)', 'Population (Hispanic)', 'Median Home Value',
       'Education (None)', 'Education (High School)', 'Education (GED)',
       'Education (Associates)', 'Education (Bachelors)',
       'Education (Masters)', 'Education (Professional)',
       'Education (Doctorate)', 'Unnamed: 0_y', 'State_y', 'Median Income',
       'Income Per Capita', 'Pop in Labor Force', 'Pop not in Labor Force',
       'Unemployed', 'Median Age', 'Median Age (male)', 'Median Age (female)'],
      dtype='object')

In [55]:
# Drop columns that are not needed
merged_file3 = merged_file2.drop(["Unnamed: 0_x", "Unnamed: 0_y", "State_y"], axis = 1)

In [56]:
# Rename columns
merged_file3.rename(columns=
                   {"County":"County",
                    "State_x":"State",
                   "votes_dem":"DEM Votes",
                   "votes_gop":"GOP Votes",
                   "total_votes":"Total Votes",
                   "per_dem":"DEM %",
                   "per_gop":"GOP %",
                   "state_abbr":"State Abbr",                   
                   "Total Population":"Total Population",
                   "Population (White)":"Population (White)",
                   "Population (African-American)":"Population (African-American)",
                   "Population (Asian)":"Population (Asian)",
                   "Population (Hispanic)":"Population (Hispanic)",
                   "Median Home Value":"Median Home Value",
                   "Education (None)":"Education (None)",
                   "Education (High School)":"Education (High School)",
                   "Education (GED)":"Education (GED)",
                   "Education (Associates)":"Education (Associates)",
                   "Education (Bachelors)":"Education (Bachelors)",
                   "Education (Masters)":"Education (Masters)",
                   "Education (Professional)":"Education (Professional)",
                   "Education (Doctorate)":"Education (Doctorate)",
                   "Median Income":"Median Income",
                   "Income Per Capita":"Income Per Capita",
                   "Pop in Labor Force":"Pop in Labor Force",
                   "Pop not in Labor Force":"Pop Not in Labor Force",
                   "Unemployed":"Unemployed",
                   "Median Age":"Median Age",
                   "Median Age (male)":"Median Age (Male)",
                   "Median Age (female)":"Median Age (Female)"},
                   inplace=True)

In [57]:
merged_file3.columns

Index(['DEM Votes', 'GOP Votes', 'Total Votes', 'DEM %', 'GOP %', 'State Abbr',
       'County', 'State', 'Total Population', 'Population (White)',
       'Population (African-American)', 'Population (Asian)',
       'Population (Hispanic)', 'Median Home Value', 'Education (None)',
       'Education (High School)', 'Education (GED)', 'Education (Associates)',
       'Education (Bachelors)', 'Education (Masters)',
       'Education (Professional)', 'Education (Doctorate)', 'Median Income',
       'Income Per Capita', 'Pop in Labor Force', 'Pop Not in Labor Force',
       'Unemployed', 'Median Age', 'Median Age (Male)', 'Median Age (Female)'],
      dtype='object')

In [59]:
# Reorganizing the columns using double brackets
merged_file = merged_file3[['State', 'State Abbr','County', 'DEM Votes', 'GOP Votes', 'Total Votes', 'DEM %', 'GOP %', 
       'Total Population', 'Population (White)', 'Population (African-American)', 'Population (Asian)',
       'Population (Hispanic)', 'Median Age', 'Median Age (Male)', 'Median Age (Female)',
        'Education (None)', 'Education (High School)', 'Education (GED)', 'Education (Associates)',
       'Education (Bachelors)', 'Education (Masters)','Education (Professional)', 'Education (Doctorate)',
        'Median Income', 'Income Per Capita', 'Median Home Value',
        'Pop in Labor Force', 'Pop Not in Labor Force', 'Unemployed', ]]
merged_file.head()

,State,State Abbr,County,DEM Votes,GOP Votes,Total Votes,DEM %,GOP %,Total Population,Population (White),...,Education (Bachelors),Education (Masters),Education (Professional),Education (Doctorate),Median Income,Income Per Capita,Median Home Value,Pop in Labor Force,Pop Not in Labor Force,Unemployed
0,Indiana,IN,Adams County,2802,9642,13039,0.214894,0.739474,34813.0,33743.0,...,2311.0,768.0,126.0,64.0,47572.0,21173.0,114600.0,15975.0,8948.0,872.0
1,Indiana,IN,Allen County,55222,83801,145787,0.378785,0.574818,365565.0,290987.0,...,42160.0,16367.0,4152.0,1694.0,49574.0,26058.0,116400.0,186706.0,93216.0,13152.0
2,Indiana,IN,Bartholomew County,9841,20637,32389,0.303838,0.637161,80203.0,69108.0,...,9685.0,5255.0,499.0,632.0,55874.0,28631.0,137500.0,41710.0,21169.0,2165.0
3,Indiana,IN,Benton County,860,2579,3654,0.235359,0.705802,8709.0,8516.0,...,753.0,188.0,42.0,12.0,48069.0,23181.0,81500.0,4368.0,2364.0,201.0
4,Indiana,IN,Blackford County,1243,3349,4822,0.257777,0.694525,12364.0,12036.0,...,546.0,315.0,51.0,42.0,38791.0,21980.0,67100.0,5763.0,4263.0,480.0

In [60]:
merged_file.shape

(92, 30)

In [61]:
merged_file.columns

Index(['State', 'State Abbr', 'County', 'DEM Votes', 'GOP Votes',
       'Total Votes', 'DEM %', 'GOP %', 'Total Population',
       'Population (White)', 'Population (African-American)',
       'Population (Asian)', 'Population (Hispanic)', 'Median Age',
       'Median Age (Male)', 'Median Age (Female)', 'Education (None)',
       'Education (High School)', 'Education (GED)', 'Education (Associates)',
       'Education (Bachelors)', 'Education (Masters)',
       'Education (Professional)', 'Education (Doctorate)', 'Median Income',
       'Income Per Capita', 'Median Home Value', 'Pop in Labor Force',
       'Pop Not in Labor Force', 'Unemployed'],
      dtype='object')

In [62]:
merged_file.count()

State                            92
State Abbr                       92
County                           92
DEM Votes                        92
GOP Votes                        92
Total Votes                      92
DEM %                            92
GOP %                            92
Total Population                 92
Population (White)               92
Population (African-American)    92
Population (Asian)               92
Population (Hispanic)            92
Median Age                       92
Median Age (Male)                92
Median Age (Female)              92
Education (None)                 92
Education (High School)          92
Education (GED)                  92
Education (Associates)           92
Education (Bachelors)            92
Education (Masters)              92
Education (Professional)         92
Education (Doctorate)            92
Median Income                    92
Income Per Capita                92
Median Home Value                92
Pop in Labor Force               92
Pop Not in Labor Force           92
Unemployed                       92
dtype: int64

In [63]:
merged_file.to_csv("merged_file.csv")