In [43]:
# import in and read indiana_census.csv and 2016_US_County_Level_Presidential_Results.csv files
import pandas as pd
import requests
import json
import csv

election_results_file = "in_clean_result.csv"
indiana_census_file = "indiana_census.csv"

election_results_df = pd.read_csv(election_results_file)
indiana_census_df = pd.read_csv(indiana_census_file)

In [44]:
election_results_df.head()

,votes_dem,votes_gop,total_votes,per_dem,per_gop,state_abbr,county_name
0,2802.0,9642.0,13039.0,0.214894,0.739474,IN,Adams County
1,55222.0,83801.0,145787.0,0.378785,0.574818,IN,Allen County
2,9841.0,20637.0,32389.0,0.303838,0.637161,IN,Bartholomew County
3,860.0,2579.0,3654.0,0.235359,0.705802,IN,Benton County
4,1243.0,3349.0,4822.0,0.257777,0.694525,IN,Blackford County

In [45]:
# Clean up county_name category. Replace 'county_name' with 'County'
election_results_df.rename(columns={"county_name":"County"}, inplace=True)
election_results_df.columns

Index(['votes_dem', 'votes_gop', 'total_votes', 'per_dem', 'per_gop',
       'state_abbr', 'County'],
      dtype='object')

In [46]:
election_results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 7 columns):
votes_dem      92 non-null float64
votes_gop      92 non-null float64
total_votes    92 non-null float64
per_dem        92 non-null float64
per_gop        92 non-null float64
state_abbr     92 non-null object
County         92 non-null object
dtypes: float64(5), object(2)
memory usage: 5.2+ KB

In [47]:
indiana_census_df.head()

,Unnamed: 0,State,County,Total Population,Population (White),Population (African-American),Population (Asian),Population (Hispanic),Median Home Value,Education (None),Education (High School),Education (GED),Education (Associates),Education (Bachelors),Education (Masters),Education (Professional),Education (Doctorate)
0,759,Indiana,Adams County,34813.0,33743.0,247.0,121.0,1533.0,114600.0,217.0,7627.0,1088.0,1594.0,2311.0,768.0,126.0,64.0
1,760,Indiana,Allen County,365565.0,290987.0,42168.0,12228.0,25810.0,116400.0,2265.0,58807.0,9682.0,23158.0,42160.0,16367.0,4152.0,1694.0
2,761,Indiana,Bartholomew County,80203.0,69108.0,1522.0,4585.0,5079.0,137500.0,527.0,15840.0,3056.0,4588.0,9685.0,5255.0,499.0,632.0
3,762,Indiana,Benton County,8709.0,8516.0,80.0,18.0,449.0,81500.0,23.0,2325.0,304.0,471.0,753.0,188.0,42.0,12.0
4,763,Indiana,Blackford County,12364.0,12036.0,75.0,38.0,176.0,67100.0,47.0,3748.0,447.0,755.0,546.0,315.0,51.0,42.0

In [48]:
indiana_census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 17 columns):
Unnamed: 0                       92 non-null int64
State                            92 non-null object
County                           92 non-null object
Total Population                 92 non-null float64
Population (White)               92 non-null float64
Population (African-American)    92 non-null float64
Population (Asian)               92 non-null float64
Population (Hispanic)            92 non-null float64
Median Home Value                92 non-null float64
Education (None)                 92 non-null float64
Education (High School)          92 non-null float64
Education (GED)                  92 non-null float64
Education (Associates)           92 non-null float64
Education (Bachelors)            92 non-null float64
Education (Masters)              92 non-null float64
Education (Professional)         92 non-null float64
Education (Doctorate)            92 non-null float64
dtypes: float64(14), int64(1), object(2)
memory usage: 12.3+ KB



MARKDOWN NOTE:

Census breakdowns for each of us to complete various plots:
Allyson - Age & Employment         NEED AGE & EMPLOYMENT added to indiana_census_file
Nirmal - Income & Race/Ethnicity   NEED INCOME added to indiana_census_file
Michael - Education & Home Value   both are included

Allyson - probably my fault for not slacking these over. sorry.  I will look for these census categories and slack them out. - MRD

In [49]:
# Merge two dataframes using an outer join
merged_file = pd.merge(election_results_df, indiana_census_df, on="County", how="outer")

In [50]:
merged_file.head()

,votes_dem,votes_gop,total_votes,per_dem,per_gop,state_abbr,County,Unnamed: 0,State,Total Population,...,Population (Hispanic),Median Home Value,Education (None),Education (High School),Education (GED),Education (Associates),Education (Bachelors),Education (Masters),Education (Professional),Education (Doctorate)
0,2802.0,9642.0,13039.0,0.214894,0.739474,IN,Adams County,759,Indiana,34813.0,...,1533.0,114600.0,217.0,7627.0,1088.0,1594.0,2311.0,768.0,126.0,64.0
1,55222.0,83801.0,145787.0,0.378785,0.574818,IN,Allen County,760,Indiana,365565.0,...,25810.0,116400.0,2265.0,58807.0,9682.0,23158.0,42160.0,16367.0,4152.0,1694.0
2,9841.0,20637.0,32389.0,0.303838,0.637161,IN,Bartholomew County,761,Indiana,80203.0,...,5079.0,137500.0,527.0,15840.0,3056.0,4588.0,9685.0,5255.0,499.0,632.0
3,860.0,2579.0,3654.0,0.235359,0.705802,IN,Benton County,762,Indiana,8709.0,...,449.0,81500.0,23.0,2325.0,304.0,471.0,753.0,188.0,42.0,12.0
4,1243.0,3349.0,4822.0,0.257777,0.694525,IN,Blackford County,763,Indiana,12364.0,...,176.0,67100.0,47.0,3748.0,447.0,755.0,546.0,315.0,51.0,42.0

In [51]:
merged_file.shape

(92, 23)

In [52]:
merged_file.columns

Index(['votes_dem', 'votes_gop', 'total_votes', 'per_dem', 'per_gop',
       'state_abbr', 'County', 'Unnamed: 0', 'State', 'Total Population',
       'Population (White)', 'Population (African-American)',
       'Population (Asian)', 'Population (Hispanic)', 'Median Home Value',
       'Education (None)', 'Education (High School)', 'Education (GED)',
       'Education (Associates)', 'Education (Bachelors)',
       'Education (Masters)', 'Education (Professional)',
       'Education (Doctorate)'],
      dtype='object')

In [53]:
merged_file.count()

votes_dem                        92
votes_gop                        92
total_votes                      92
per_dem                          92
per_gop                          92
state_abbr                       92
County                           92
Unnamed: 0                       92
State                            92
Total Population                 92
Population (White)               92
Population (African-American)    92
Population (Asian)               92
Population (Hispanic)            92
Median Home Value                92
Education (None)                 92
Education (High School)          92
Education (GED)                  92
Education (Associates)           92
Education (Bachelors)            92
Education (Masters)              92
Education (Professional)         92
Education (Doctorate)            92
dtype: int64

In [54]:
merged_file.to_csv("merged_file.csv")